version: '3'

services:
  influxdb-server:
    build: ./influxdb-server
    ports:
    - "8086:8086"
  influxdb-frontend:
    build: ./influxdb-frontend
    ports:
    - "80:3000"
    depends_on:
    - influxdb-server
  telegraf-collector:
    build: ./telegraf-collector
    ports:
    - "8186:8186"
    depends_on:
    - influxdb-server
    environment:
    - INFLUXDB_HOST=influxdb-server
    - GROUP_NAME=telegraf-collector
    volumes:
    - ./telegraf-collector/app:/srv/app

  nats-server:
    build: ./nats-server
    ports:
    - "4442:4442"
    - "8222:8222"
  nats-producer:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    command:
    - ./bin/run-app
    - nats-producer
    volumes:
    - ./worker/app:/srv/app
  nats-consumer:
    build: ./worker
    ports:
    - "8080:80"
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    - APP_PORT=80
    command:
    - ./bin/run-app
    - nats-consumer
    volumes:
    - ./worker/app:/srv/app
  nats-benchmarker:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    command:
    - ./bin/run-app
    - nats-benchmarker
    volumes:
    - ./worker/app:/srv/app
  nats-consumer-benchmark:
    build: ./benchmark
    volumes:
    - ./benchmark/app:/srv/app
  nats-top:
    image: byrnedo/nats-top
    depends_on:
    - nats-server
    command: ["-s", "nats-server"]

  # reads influxdb writes out of a nats queue
  influxdb-buffer:
    build: ./influxdb-buffer
    depends_on:
    - influxdb-server
    - nats-server
    environment:
    - INFLUX_HOST=influxdb-server
    - INFLUX_PORT=8086
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    volumes:
    - ./influxdb-buffer:/go/src/influxdb-buffer

  # monitors an instance of nats and reports usage stats to influx
  nats-monitor:
    build: ./nats-monitor
    depends_on:
    - influxdb-server
    - nats-server
    environment:
    - INFLUX_HOST=influxdb-server
    - INFLUX_PORT=8086
    - NATS_HOST=nats-server
    - NATS_INFO_PORT=8222
    volumes:
    - ./nats-monitor/app:/go/src/nats-monitor
