version: '3'

services:
  kafka-zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka-server:
    depends_on:
    - kafka-zookeeper
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
    - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
  kafka-producer:
    build: ./kafka-producer
  kafka-consumer:
    build: ./kafka-consumer
    ports:
    - "80:80"

  nats-server:
    image: nats-streaming
    ports:
    - "4222:4222"
  nats-producer:
    build: ./nats-producer
    depends_on:
    - nats-server
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    volumes:
    - ./nats-producer/app:/srv/app
  nats-consumer:
    build: ./nats-consumer
    depends_on:
    - nats-server
    - nats-producer
    ports:
    - "80:80"
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - APP_PORT=80
    volumes:
    - ./nats-consumer/app:/srv/app
