version: '3'

services:
  influxdb-server:
    build: ./influxdb-server
    ports:
    - "8086:8086"
  influxdb-frontend:
    build: ./influxdb-frontend
    ports:
    - "80:3000"
    depends_on:
    - influxdb-server
  telegraf-collector:
    build: ./telegraf-collector
    ports:
    - "8186:8186"
    depends_on:
    - influxdb-server
    environment:
    - INFLUXDB_HOST=influxdb-server
    - GROUP_NAME=telegraf-collector
    volumes:
    - ./telegraf-collector/app:/srv/app

  kafka-zookeeper:
    image: wurstmeister/zookeeper
  kafka-server:
    depends_on:
    - kafka-zookeeper
    image: wurstmeister/kafka
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
    - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
  kafka-producer:
    build: ./kafka-producer
  kafka-consumer:
    build: ./kafka-consumer

  nats-server:
    build: ./nats-server
    ports:
    - "4442:4442"
  nats-producer:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    entrypoint:
    - ""
    # - ./bin/run-app
    command:
    - nats-producer
    volumes:
    - ./worker/app:/srv/app
  nats-consumer:
    build: ./worker
    ports:
    - "8080:80"
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    - APP_PORT=80
    entrypoint:
    # - ./bin/run-app
    - ""
    command:
    - nats-consumer
    volumes:
    - ./worker/app:/srv/app
  nats-benchmarker:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    entrypoint:
    # - ./bin/run-app
    - ""
    command:
    - nats-benchmarker
    volumes:
    - ./worker/app:/srv/app
  nats-consumer-benchmark:
    build: ./benchmark
    volumes:
    - ./benchmark/app:/srv/app
  nats-top:
    image: byrnedo/nats-top
    depends_on:
    - nats-server
    command: ["-s", "nats-server"]

  # reads influxdb writes out of a nats queue
  influxdb-buffer:
    build: ./influxdb-buffer
    depends_on:
    - influxdb-server
    - nats-server
    environment:
    - INFLUX_HOST=influxdb-server
    - INFLUX_PORT=8086
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    volumes:
    - ./influxdb-buffer:/go/src/influxdb-buffer
