version: '3'

services:
  influxdb-server:
    build: ./influxdb-server
    ports:
    - "8086:8086"
  influxdb-frontend:
    build: ./influxdb-frontend
    ports:
    - "80:3000"
    depends_on:
    - influxdb-server
  telegraf-collector:
    build: ./telegraf-collector
    ports:
    - "8186:8186"
    depends_on:
    - influxdb-server
    environment:
    - INFLUXDB_HOST=influxdb-server
    - GROUP_NAME=telegraf-collector
    volumes:
    - ./telegraf-collector/app:/srv/app

  # nats server
  nats-server:
    build: ./nats-server
    ports:
    - "4442:4442"
    - "8222:8222"

  # rabbit server
  rabbit-server:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_VHOST=ecp4

  # monitors an instance of nats&rabbit and reports usage stats to influx
  message-bus-monitor:
    build: ./message-bus-monitor
    depends_on:
    - influxdb-server
    - nats-server
    - rabbit-server
    environment:
    - INFLUX_HOST=influxdb-server
    - INFLUX_PORT=8086
    - NATS_HOST=nats-server
    - NATS_PORT=8222
    - RABBIT_HOST=rabbit-server
    - RABBIT_PORT=15672
    volumes:
    - ./message-bus-monitor/app:/go/src/message-bus-monitor

  # reads influxdb writes out of a nats queue
  influxdb-buffer:
    build: ./influxdb-buffer
    depends_on:
    - influxdb-server
    - nats-server
    environment:
    - INFLUX_HOST=influxdb-server
    - INFLUX_PORT=8086
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    volumes:
    - ./influxdb-buffer:/go/src/influxdb-buffer
