version: '3'

services:
  kafka-zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
    - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - kafka-zookeeper
  kafka-producer:
    build: ./kafka-producer
  kafka-consumer:
    build: ./kafka-consumer
    ports:
    - "80:80"

  nats-server:
    image: nats
    ports:
    - "4222:4222"
  nats-producer:
    build: ./nats-producer
    volumes:
    - ./nats-producer/app:/srv/app
    depends_on:
    - nats-server
  nats-consumer:
    build: ./nats-consumer
    ports:
    - "80:80"
