version: '3'

services:
  # provides a top-like interface to visually monitoring nats
  nats-top:
    image: byrnedo/nats-top
    depends_on:
    - nats-server
    command: ["-s", "nats-server"]

  # worker-based apps
  nats-producer:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    command:
    - ./bin/run-app
    - nats-producer
    volumes:
    - ./worker/app:/srv/app
  nats-consumer:
    build: ./worker
    ports:
    - "8080:80"
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    - APP_PORT=80
    command:
    - ./bin/run-app
    - nats-consumer
    volumes:
    - ./worker/app:/srv/app
  nats-dev:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    - DRIVER_TYPE=nats
    command:
    - bash
    volumes:
    - ./worker/app:/srv/app
  nats-benchmarker:
    build: ./worker
    depends_on:
    - nats-server
    - influxdb-buffer
    environment:
    - NATS_HOST=nats-server
    - NATS_PORT=4222
    - METRICS_HOST=nats-server
    - METRICS_PORT=4222
    command:
    - ./bin/run-app
    - nats-benchmarker
    - -d 2m
    - -w 200
    volumes:
    - ./worker/app:/srv/app
  
  # siege-based app for benchmarking the consumer api
  nats-consumer-benchmark:
    build: ./benchmark
    volumes:
    - ./benchmark/app:/srv/app
